//! Golden-vector test against the original C++ implementation.
//!
//! `tests/data/vectors.txt` is generated by `tools/gen_vectors.py` from a harness linked
//! against the unmodified udp2raw C++ sources (see `tools/cpp_harness/`). Every cipher ×
//! auth mode × role combination is covered.

use udp2raw::crypto::{AuthMode, CipherMode, Crypto, Keys};
use udp2raw::util::{hex, unhex};

fn hex_or_dash(v: &[u8]) -> String {
    if v.is_empty() { "-".to_string() } else { hex(v) }
}

struct Cfg {
    role_client: bool,
    cipher: CipherMode,
    auth: AuthMode,
    password: String,
    cfb_legacy: bool,
}

impl Cfg {
    fn crypto(&self, client: bool) -> Crypto {
        Crypto::new(self.cipher, self.auth, self.cfb_legacy, Keys::derive(&self.password, client))
    }
}

#[test]
fn golden_vectors_from_cpp() {
    let text = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data/vectors.txt"))
        .expect("tests/data/vectors.txt missing — run tools/gen_vectors.py");
    let mut cfg: Option<Cfg> = None;
    let mut me: Option<Crypto> = None; // the CFG role
    let mut other: Option<Crypto> = None; // the opposite role
    let mut checked = 0usize;
    for (lineno, line) in text.lines().enumerate() {
        let f: Vec<&str> = line.split(' ').collect();
        let ctx = || format!("line {}: {}", lineno + 1, &line[..line.len().min(120)]);
        match f[0] {
            "CFG" => {
                let (cipher, legacy_from_name) = CipherMode::parse(f[2]).unwrap();
                let c = Cfg {
                    role_client: f[1] == "client",
                    cipher,
                    auth: AuthMode::parse(f[3]).unwrap(),
                    password: String::from_utf8(unhex(f[4]).unwrap()).unwrap(),
                    cfb_legacy: legacy_from_name || f[5] == "1",
                };
                me = Some(c.crypto(c.role_client));
                other = Some(c.crypto(!c.role_client));
                cfg = Some(c);
            }
            "KEY" => {
                let k = me.as_ref().unwrap().keys();
                let want = unhex(f[2]).unwrap();
                let got: &[u8] = match f[1] {
                    "normal_key" => &k.normal_key,
                    "cipher_key_encrypt" => &k.cipher_key_encrypt,
                    "cipher_key_decrypt" => &k.cipher_key_decrypt,
                    "hmac_key_encrypt" => &k.hmac_key_encrypt,
                    "hmac_key_decrypt" => &k.hmac_key_decrypt,
                    _ => panic!("unknown key {}", f[1]),
                };
                assert_eq!(hex(got), hex(&want), "{} ({})", f[1], ctx());
                checked += 1;
            }
            "GROXOR" => {
                assert_eq!(hex(&me.as_ref().unwrap().keys().gro_xor), f[1], "{}", ctx());
                checked += 1;
            }
            "ECB" => {
                if cfg.as_ref().unwrap().cipher.is_aes() {
                    let m = me.as_ref().unwrap();
                    let mut b = unhex(f[1]).unwrap();
                    m.ecb_encrypt1(&mut b);
                    assert_eq!(hex(&b), f[2], "ecbenc {}", ctx());
                    let mut b = unhex(f[1]).unwrap();
                    m.ecb_decrypt1(&mut b);
                    assert_eq!(hex(&b), f[3], "ecbdec {}", ctx());
                    checked += 1;
                }
            }
            "ENC" => {
                let c = cfg.as_ref().unwrap();
                let m = me.as_ref().unwrap();
                let plain = unhex(f[1]).unwrap();
                let got = m.encrypt(&plain);
                if f[2] == "ERR" {
                    assert!(got.is_none(), "expected ERR: {}", ctx());
                } else {
                    let want = unhex(f[2]).unwrap();
                    let got = got.unwrap_or_else(|| panic!("encrypt failed: {}", ctx()));
                    assert_eq!(got.len(), want.len(), "length: {}", ctx());
                    if c.cipher == CipherMode::Aes128Cbc {
                        // The C++ pads with uninitialised bytes, so the last CBC block differs
                        // (and, with encrypt-then-MAC, the trailing 20-byte tag over it).
                        // Everything before the last CBC block must match exactly …
                        let tag = if c.auth == AuthMode::HmacSha1 { 20 } else { 0 };
                        let n = got.len() - tag - 16;
                        assert_eq!(hex(&got[..n]), hex(&want[..n]), "cbc prefix: {}", ctx());
                        // … and the peer must decrypt both to the same plaintext.
                        assert_eq!(other.as_ref().unwrap().decrypt(&got).as_deref(), Some(&plain[..]), "peer decrypt of our cbc: {}", ctx());
                    } else {
                        assert_eq!(hex(&got), hex(&want), "{}", ctx());
                    }
                }
                checked += 1;
            }
            "XDEC" => {
                let o = other.as_ref().unwrap();
                let ct = unhex(f[1]).unwrap();
                let got = o.decrypt(&ct);
                if f[2] == "ERR" {
                    assert!(got.is_none(), "expected decrypt ERR: {}", ctx());
                } else {
                    assert_eq!(got.map(|v| hex_or_dash(&v)).as_deref(), Some(f[2]), "{}", ctx());
                }
                checked += 1;
            }
            "TDEC" => {
                let o = other.as_ref().unwrap();
                let ct = unhex(f[1]).unwrap();
                let got = o.decrypt(&ct);
                if f[2] == "ERR" {
                    assert!(got.is_none(), "tampered packet accepted: {}", ctx());
                } else {
                    // no integrity protection in this mode: must produce the same garbage
                    assert_eq!(got.map(|v| hex_or_dash(&v)).as_deref(), Some(f[2]), "{}", ctx());
                }
                checked += 1;
            }
            "" => {}
            other_tag => panic!("unknown record {other_tag}: {}", ctx()),
        }
    }
    assert!(checked > 1000, "only {checked} vectors checked");
}
